# Jekyll Resume Theme

# Site settings
title: Taehyung Resume
email: opencv@kakao.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Taehyung Kim
job: AI researcher & development
location: Birmingham, UK
languages: C++, C#, python
twitter_username: boysboy3
github_username:  kimtaehyeong
codepen_username:  mattcouchman
email_address: opencv@kakao.com

# Build settings
markdown: kramdown
