# Jekyll Resume Theme

# Site settings
title: Taehyung Resume
email: opencv@kakao.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
name: Taehyung Kim
job: AI researcher & development
location: Seoul, Republic of Korea
languages: C++, C#, python
github_username:  kimtaehyeong
email_address: opencv@kakao.com

# Build settings
markdown: kramdown
